In [1]:
import pandas as pd

In [2]:
sigdmp_df = pd.read_excel("./data/intersection_lists/merged_unique_DMPs.xlsx")
sigdmp_df

    significant DMPs
0    cg10357235_BC21
1    cg23059725_TC21
2    cg02547794_TC21
3    cg23584554_TC21
4    cg18428180_BC11
..               ...
623  cg15455300_TC21
624  cg09910635_TC21
625  cg24586899_TC21
626  cg26427777_BC21
627  cg19724910_BC11

[628 rows x 1 columns]

In [3]:
epicv2_meta = pd.read_excel("./data/EPICv2_source_data.xlsx", index_col=0)
epicv2_meta

,ID_source,chr,pos,strand,Relation_to_Island,HMM_Island,Regulatory_Feature_Group,Phantom5_Enhancers,Methyl450_Enhancer,Methyl450_Loci,EPICv1_Loci
cg25324105_BC11,cg25324105_BC11,chr19,37692358,+,Island,NaN,Unclassified_Cell_type_specific,NaN,True,cg25324105,cg25324105
cg25383568_TC11,cg25383568_TC11,chr19,38727081,-,Island,NaN,Gene_Associated_Cell_type_specific,NaN,True,cg25383568,cg25383568
cg25455143_BC11,cg25455143_BC11,chr19,1591515,-,Island,NaN,NaN,NaN,False,cg25455143,cg25455143
cg25459778_BC11,cg25459778_BC11,chr16,1614581,+,Island,NaN,NaN,NaN,False,cg25459778,cg25459778
cg25487775_BC11,cg25487775_BC11,chr2,161237458,+,Shore,NaN,NaN,NaN,False,cg25487775,cg25487775
...,...,...,...,...,...,...,...,...,...,...,...
ch.22.16108507R_BC21,ch.22.16108507R_BC21,chr22,17247617,+,OpenSea,NaN,NaN,NaN,False,NaN,ch.22.16108507R
ch.22.40657F_BC21,ch.22.40657F_BC21,chr22,17685590,-,OpenSea,NaN,NaN,NaN,False,NaN,ch.22.40657F
ch.22.78028F_BC21,ch.22.78028F_BC21,chr22,19374531,-,OpenSea,NaN,NaN,NaN,False,NaN,ch.22.78028F
ch.22.17803970R_BC21,ch.22.17803970R_BC21,chr22,19436447,+,Shelf,NaN,NaN,NaN,False,NaN,ch.22.17803970R
ch.22.107403R_TC21,ch.22.107403R_TC21,chr22,20144102,+,Shore,NaN,NaN,NaN,False,NaN,ch.22.107403R

In [4]:
significant_dmps = sigdmp_df['significant DMPs'].values

In [5]:
# Filter df2 to keep only rows where the index is in significant_dmps
epicv2_meta = epicv2_meta[epicv2_meta.index.isin(significant_dmps)]
epicv2_meta

,ID_source,chr,pos,strand,Relation_to_Island,HMM_Island,Regulatory_Feature_Group,Phantom5_Enhancers,Methyl450_Enhancer,Methyl450_Loci,EPICv1_Loci
cg11715903_TC11,cg11715903_TC11,chr14,52950609,-,Island,NaN,NaN,NaN,False,cg11715903,cg11715903
cg11206167_TC11,cg11206167_TC11,chr5,42924265,+,Island,NaN,NaN,NaN,False,cg11206167,cg11206167
cg13563793_BC11,cg13563793_BC11,chr20,25696946,-,Island,NaN,Promoter_Associated,NaN,True,cg13563793,cg13563793
cg16920238_TC11,cg16920238_TC11,chr17,82118502,+,OpenSea,NaN,NaN,NaN,False,cg16920238,cg16920238
cg17112089_TC11,cg17112089_TC11,chr7,117873294,-,Island,NaN,NaN,NaN,False,cg17112089,cg17112089
...,...,...,...,...,...,...,...,...,...,...,...
cg08949101_BC21,cg08949101_BC21,chr21,32585647,-,OpenSea,NaN,NaN,NaN,False,cg08949101,cg08949101
cg03162465_BC21,cg03162465_BC21,chr11,5789982,+,OpenSea,NaN,NaN,NaN,False,NaN,cg03162465
cg03147584_TC21,cg03147584_TC21,chr1,247748422,-,OpenSea,NaN,NaN,NaN,False,NaN,cg03147584
cg03131255_TC21,cg03131255_TC21,chr2,89822132,-,OpenSea,NaN,NaN,NaN,False,NaN,NaN
ch.15.79573225R_TC21,ch.15.79573225R_TC21,chr15,81493829,+,OpenSea,NaN,NaN,NaN,False,NaN,ch.15.79573225R

In [10]:
non_nan_count = epicv2_meta['Methyl450_Loci'].count()
non_nan_count

np.int64(452)

In [ ]:
# Replace all NaN values with the word "Unknown"
epicv2_meta = epicv2_meta.fillna("Unknown")
epicv2_meta

In [ ]:
epicv2_meta = epicv2_meta.replace("Unknown", "N/A")
epicv2_meta

In [11]:
epicv2_meta.to_excel("./data/significant_dmps_epicv2_metadata.xlsx", index=False)